---
# tasks file for hswong3i.memcached

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "memcached" }
  notify: restart memcached
  tags: hswong3i.memcached

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/default/memcached.j2", dest: "/etc/default/memcached", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/memcached.conf.j2", dest: "/etc/memcached.conf", owner: "root", group: "root", mode: "0644" }
  notify: restart memcached
  tags: hswong3i.memcached

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "memcached", enabled: "yes" }
  notify: restart memcached
  tags: hswong3i.memcached
